#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Install CentOS7' {
        set root='hd2,gpt2'
        linuxefi /vmlinuz-ks ks=http://10.73.25.3/snippets/5/raw
        initrdefi /initrd-ks.img
}